[package]
name = "real-ip"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/icewind1991/real-ip"
license = "MIT OR Apache-2.0"
rust-version = "1.60.0"

[dependencies]
http = "1.1.0"
rfc7239 = "0.1.2"
comma-separated = "0.1.0"
ipnet = "2.10.1"
itertools = "0.13.0"
